
FISICA

Desafio("Qual das opções abaixo é a unidade de potência?", {'a': 'Newton', 'b': 'Pascal', 'c': 'Watt', 'd': 'Joule'}, 'c'),
Desafio("Qual é a fórmula da velocidade média?", {'a': 'v = d + t', 'b': 'v = d / t', 'c': 'v = t / d', 'd': 'v = d * t'}, 'b'),
Desafio("A energia cinética é calculada como:", {'a': 'E_c = mgh', 'b': 'E_c = m + v', 'c': 'E_c = mv^2 / 2', 'd': 'E_c = v^2 / m'}, 'c'),
Desafio("A segunda lei de Newton estabelece que a força é:", {'a': 'Proporcional à massa', 'b': 'Proporcional ao deslocamento', 'c': 'Proporcional à velocidade', 'd': 'Inversamente proporcional à aceleração'}, 'a'),
Desafio("A unidade de pressão no Sistema Internacional é:", {'a': 'Joule', 'b': 'Newton', 'c': 'Watt', 'd': 'Pascal'}, 'd'),
Desafio("No movimento retilíneo uniformemente variado, qual é a principal característica?", {'a': 'Aceleração constante', 'b': 'Velocidade constante', 'c': 'Trajetória circular', 'd': 'Força constante'}, 'a'),
Desafio("A unidade de energia no Sistema Internacional é:", {'a': 'Pascal', 'b': 'Newton', 'c': 'Joule', 'd': 'Watt'}, 'c'),
Desafio("O que a terceira lei de Newton afirma?", {'a': 'Força é igual a massa vezes aceleração', 'b': 'Aceleração é constante', 'c': 'A energia é conservada', 'd': 'Para toda ação, há uma reação igual e oposta'}, 'd'),
Desafio("Qual é a fórmula do trabalho realizado por uma força constante?", {'a': 'W = F + d', 'b': 'W = F * d', 'c': 'W = d / F', 'd': 'W = F / d'}, 'b'),
Desafio("Qual a unidade de velocidade no Sistema Internacional?", {'a': 'm/s', 'b': 'm/s²', 'c': 'Newton', 'd': 'Joule'}, 'a'),
Desafio("A energia potencial gravitacional de um corpo é dada por:", {'a': 'E_p = mv^2 / 2', 'b': 'E_p = mg * v', 'c': 'E_p = mgh', 'd': 'E_p = v / m'}, 'c'),
Desafio("O que representa o princípio da conservação da energia?", {'a': 'Energia é sempre crescente', 'b': 'Energia depende do calor', 'c': 'Energia não pode ser criada nem destruída, apenas transformada', 'd': 'Energia é perdida com o tempo'}, 'c'),
Desafio("Qual é a fórmula da aceleração?", {'a': 'a = v * t', 'b': 'a = Δv / Δt', 'c': 'a = v / t', 'd': 'a = d / t'}, 'b'),
Desafio("Em um circuito elétrico, a unidade de corrente elétrica é:", {'a': 'Watt', 'b': 'Ampère', 'c': 'Volt', 'd': 'Ohm'}, 'b'),
Desafio("O que representa o momento linear?", {'a': 'Produto da massa pelo volume', 'b': 'Produto da velocidade pelo tempo', 'c': 'Produto da massa pela velocidade', 'd': 'Produto da força pela aceleração'}, 'c'),
Desafio("Qual a unidade de resistência elétrica?", {'a': 'Volt', 'b': 'Ohm', 'c': 'Joule', 'd': 'Newton'}, 'b'),
Desafio("A potência elétrica de um circuito é dada por:", {'a': 'P = V + I', 'b': 'P = V / R', 'c': 'P = V * I', 'd': 'P = V - I'}, 'c'),
Desafio("O período de uma onda é calculado como:", {'a': 'T = 1 / f', 'b': 'T = f * λ', 'c': 'T = λ / f', 'd': 'T = f + λ'}, 'a'),
Desafio("Qual é a aceleração da gravidade média na Terra?", {'a': '3,6 m/s²', 'b': '6,67 m/s²', 'c': '1,6 m/s²', 'd': '9,8 m/s²'}, 'd'),
Desafio("Qual a unidade da constante gravitacional?", {'a': 'N·m / s', 'b': 'N·m² / kg²', 'c': 'J·s / m', 'd': 'N / m²'}, 'b'),
Desafio("A fórmula da força elétrica entre duas cargas é:", {'a': 'F = k / r', 'b': 'F = k · r', 'c': 'F = k * (q₁ * q₂) / r²', 'd': 'F = k · (q₁ + q₂) / r²'}, 'c'),
Desafio("Qual é a primeira lei da termodinâmica?", {'a': 'O calor sempre flui do quente para o frio', 'b': 'A energia é conservada e a variação da energia interna é igual ao calor trocado menos o trabalho realizado', 'c': 'A entropia nunca diminui', 'd': 'A energia depende da pressão'}, 'b'),
Desafio("A unidade de frequência no Sistema Internacional é:", {'a': 'Watt', 'b': 'Newton', 'c': 'Hertz', 'd': 'Pascal'}, 'c'),
Desafio("A velocidade da luz no vácuo é aproximadamente:", {'a': '3 × 10⁵ km/s', 'b': '3 × 10⁶ m/s', 'c': '3 × 10⁸ m/s', 'd': '3 × 10⁴ km/s'}, 'c'),
Desafio("Qual a fórmula da pressão?", {'a': 'P = F · d', 'b': 'P = F / A', 'c': 'P = A / F', 'd': 'P = A / d'}, 'b'),
Desafio("A densidade de um corpo é dada por:", {'a': 'ρ = m / V', 'b': 'ρ = m + V', 'c': 'ρ = V · m', 'd': 'ρ = m - V'}, 'a'),
Desafio("A lei de Pascal é aplicada em:", {'a': 'Sistemas térmicos', 'b': 'Hidráulica', 'c': 'Ondas sonoras', 'd': 'Circuitos elétricos'}, 'b'),
Desafio("A quantidade de movimento é dada por:", {'a': 'm / v', 'b': 'm + v', 'c': 'm · v', 'd': 'm / v²'}, 'c'),
Desafio("A energia potencial elástica é dada por:", {'a': 'E = kx² / 2', 'b': 'E = k / x²', 'c': 'E = k + x²', 'd': 'E = 2kx'}, 'a'),
---------------------------------------
LOGICA


Desafio("Qual é a saída da expressão `5 + 2 * 3`?", {'a': '11', 'b': '21', 'c': '15', 'd': '17'}, 'a'),
Desafio("Qual das opções é uma estrutura de repetição em Python?", {'a': 'if', 'b': 'for', 'c': 'function', 'd': 'define'}, 'b'),
Desafio("O que faz o comando `break` em um loop?", {'a': 'Pula para a próxima iteração', 'b': 'Sai do loop', 'c': 'Finaliza o programa', 'd': 'Nada'}, 'b'),
Desafio("Qual é a função para obter o tamanho de uma lista em Python?", {'a': 'size()', 'b': 'length()', 'c': 'len()', 'd': 'count()'}, 'c'),
Desafio("O que o operador `//` faz em Python?", {'a': 'Divisão inteira', 'b': 'Módulo', 'c': 'Exponenciação', 'd': 'Divisão normal'}, 'a'),
Desafio("Como se cria um comentário em Python?", {'a': '# Este é um comentário', 'b': '// Este é um comentário', 'c': '/* Este é um comentário */', 'd': '<!-- Este é um comentário -->'}, 'a'),
Desafio("O que a função `range(5)` gera?", {'a': '5', 'b': '0, 1, 2, 3, 4', 'c': '1, 2, 3, 4, 5', 'd': '0, 1, 2, 3, 4, 5'}, 'b'),
Desafio("Qual é a saída de `print(bool(0))`?", {'a': 'True', 'b': 'False', 'c': 'Erro', 'd': 'None'}, 'b'),
Desafio("Qual é a saída de `print('2' + '2')`?", {'a': '4', 'b': '22', 'c': 'Erro', 'd': '4.0'}, 'b'),
Desafio("Qual é o tipo de dado da variável `x = [1, 2, 3]`?", {'a': 'Dicionário', 'b': 'Lista', 'c': 'Conjunto', 'd': 'Tupla'}, 'b'),
Desafio("Qual é a função utilizada para converter uma string em inteiro?", {'a': 'int()', 'b': 'str()', 'c': 'float()', 'd': 'list()'}, 'a'),
Desafio("O que é uma lista em Python?", {'a': 'Um tipo de dado imutável', 'b': 'Uma coleção ordenada e mutável', 'c': 'Uma função', 'd': 'Um tipo de dado numérico'}, 'b'),
Desafio("O que acontece se você tentar acessar um índice que não existe em uma lista?", {'a': 'Retorna None', 'b': 'Gera um erro IndexError', 'c': 'Retorna 0', 'd': 'Nada acontece'}, 'b'),
Desafio("Qual dos seguintes não é um tipo de dado em Python?", {'a': 'Lista', 'b': 'Tupla', 'c': 'Array', 'd': 'Dicionário'}, 'c'),
Desafio("Qual é a saída de `print(5 < 3)`?", {'a': 'True', 'b': 'False', 'c': 'Erro', 'd': '5'}, 'b'),
Desafio("O que significa `def` em Python?", {'a': 'Definir uma variável', 'b': 'Definir uma função', 'c': 'Definir uma classe', 'd': 'Definir um loop'}, 'b'),
Desafio("Qual é a saída de `print(2 ** 3)`?", {'a': '6', 'b': '8', 'c': '9', 'd': '7'}, 'b'),
Desafio("Qual é o método usado para adicionar um item ao final de uma lista?", {'a': 'add()', 'b': 'append()', 'c': 'insert()', 'd': 'extend()'}, 'b'),
Desafio("O que a função `sorted()` faz?", {'a': 'Ordena uma lista', 'b': 'Inverte uma lista', 'c': 'Copia uma lista', 'd': 'Remove duplicatas'}, 'a'),
Desafio("Qual é a sintaxe correta para criar um dicionário?", {'a': 'dict = []', 'b': 'dict = {}', 'c': 'dict = ()', 'd': 'dict = <>', 'b': 'b'}),
Desafio("Qual é a saída de `print('Hello'[1])`?", {'a': 'H', 'b': 'e', 'c': 'l', 'd': 'o'}, 'b'),
Desafio("O que é um tuple em Python?", {'a': 'Uma coleção mutável', 'b': 'Uma coleção ordenada e imutável', 'c': 'Um tipo de dado numérico', 'd': 'Uma função'}, 'b'),
Desafio("Qual é a saída de `print(type([]))`?", {'a': '<class \'list\'>', 'b': 'list', 'c': '[]', 'd': 'Erro'}, 'a'),
Desafio("Como se define uma função em Python?", {'a': 'function minha_funcao():', 'b': 'def minha_funcao():', 'c': 'define minha_funcao():', 'd': 'minha_funcao():', 'b'}),
Desafio("Qual é a saída de `print(3 * 'ab')`?", {'a': 'ababab', 'b': 'ab', 'c': '3', 'd': 'Erro'}, 'a'),
Desafio("Qual é a saída de `print(len('Python'))`?", {'a': '6', 'b': '7', 'c': '5', 'd': 'Erro'}, 'c'),
Desafio("Como se inicia um loop `for` em Python?", {'a': 'for i in range(5):', 'b': 'foreach i in range(5):', 'c': 'for i to range(5):', 'd': 'for i = range(5):'}, 'a'),
Desafio("O que o comando `continue` faz em um loop?", {'a': 'Pula para a próxima iteração do loop', 'b': 'Sai do loop', 'c': 'Para a execução do programa', 'd': 'Nada'}, 'a'),
Desafio("Qual é a saída de `print(10 // 3)`?", {'a': '3', 'b': '4', 'c': '3.33', 'd': 'Erro'}, 'a'),
Desafio("O que a instrução `elif` faz?", {'a': 'Representa uma condição', 'b': 'É um atalho para `if`', 'c': 'Executa um bloco de código', 'd': 'Não faz nada'}, 'a'),
Desafio("Qual é o resultado da expressão `5 != 3`?", {'a': 'True', 'b': 'False', 'c': 'Erro', 'd': 'None'}, 'a'),


